typography_spectrum: 0.21275
color:
  brandColors:
    - '#e1e1e1'
    - '#4c4c4c'
    - '#c7c7c7'
    - '#676767'
    - '#a0a0a0'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2089
analytics:
  google: null
  facebook: null
  twitter: null
name: jared
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: My Blog
    url: 'http://jaredhenriques.com'
    type: external
  - name: Renga
    url: 'http://renga.co'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: things from me
purpose: []
