name: jared
favicon: null
layout_spectrum: 0.99344
typography_spectrum: 0.6470142328180373
title: daily jared
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e1e1'
    - '#4c4c4c'
    - '#c7c7c7'
    - '#676767'
    - '#a0a0a0'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
