name: jared
favicon: null
layout_spectrum: 0.99344
typography_spectrum: 0.6470142328180373
title: daily jared
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbe4ed'
    - '#73a3d1'
    - '#071305'
    - '#3b4c1f'
    - '#e49773'
  brandStrength: 0.125
  lightness: 0.605335648637265
  saturation: 0.4720008207950741
  rhythmicContrast: 0.027008467353880405
purpose: []
